// Generated by CoffeeScript 1.9.2
var autoprefixer, gulp, minifycss, rename, sourcemaps, stylus;

gulp = require('gulp');

rename = require('gulp-rename');

sourcemaps = require('gulp-sourcemaps');

stylus = require('gulp-stylus');

autoprefixer = require('gulp-autoprefixer');

minifycss = require('gulp-minify-css');

gulp.task('default', function() {
  return gulp.src('flexy-grid.styl').pipe(sourcemaps.init()).pipe(stylus()).pipe(rename("flexy-grid.min.css")).pipe(autoprefixer({
    browsers: ['last 2 versions']
  })).pipe(minifycss({
    compatibility: '*,-properties.zeroUnits'
  })).pipe(sourcemaps.write('./')).pipe(gulp.dest('./'));
});
